# -*- coding: utf-8 -*-
"""
MEOW-SEC :: WAF — WAF / CDN Fingerprinting
  · Détecte Cloudflare, Akamai, AWS WAF, Imperva, ModSecurity...
  · Analyse headers, codes d'erreur, réponses aux payloads
  · Score de confiance + bypass hints
"""
import re, time, os, json
from datetime import datetime
from urllib.parse import urlparse

from core.ui import (console, show_module_banner, ok, err, info, warn, find,
                     ask_choice, print_result_table, G1, G2, CY, OR, RD, DM)
from core.cats import cat_talk, CAT_SCAN, CAT_FOUND
from rich.panel   import Panel
from rich.table   import Table
from rich.text    import Text
from rich.align   import Align
from rich.prompt  import Prompt, Confirm
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich         import box
from rich.rule    import Rule

try:
    import requests
    requests.packages.urllib3.disable_warnings()
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

from core.proxy_manager import px as _px

# ─── WAF SIGNATURES ──────────────────────────────────────────

WAF_DB = {
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-request-id", "cf-apo-via"],
        "server":   ["cloudflare"],
        "cookies":  ["__cfduid", "__cf_bm", "cf_clearance"],
        "body":     ["cloudflare ray id", "checking your browser", "attention required"],
        "codes":    [403, 503],
        "color":    OR,
        "bypass":   [
            "Use direct origin IP (bypass CDN)",
            "X-Forwarded-For: 127.0.0.1",
            "Origin: null header",
            "Subdomain not behind CF (e.g. mail., ftp., direct.)",
        ]
    },
    "Akamai": {
        "headers":  ["akamai-grn", "x-check-cacheable", "x-akamai-transformed",
                     "x-akamai-request-id", "x-akamai-session-info"],
        "server":   ["akamaighost", "akamai"],
        "cookies":  ["ak_bmsc", "bm_sz", "bm_sv"],
        "body":     ["akamai", "reference #", "access denied"],
        "codes":    [403],
        "color":    CY,
        "bypass":   [
            "Akamai Bot Manager can be bypassed with valid User-Agent",
            "Try TLS fingerprint rotation (JA3)",
            "Check non-Akamai subdomains",
        ]
    },
    "AWS WAF / CloudFront": {
        "headers":  ["x-amz-cf-id", "x-amz-cf-pop", "x-amzn-requestid",
                     "x-amzn-trace-id", "via"],
        "server":   ["awselb", "cloudfront"],
        "cookies":  ["aws-waf-token"],
        "body":     ["aws cloudfront", "request blocked", "error from cloudfront"],
        "codes":    [403, 405],
        "color":    "#FF9900",
        "bypass":   [
            "AWS WAF rules are custom — identify rule type first",
            "Try case variation in headers/params",
            "JSON body may bypass SQL/XSS rules",
        ]
    },
    "Imperva / Incapsula": {
        "headers":  ["x-iinfo", "x-cdn", "incap-ses", "visid_incap"],
        "server":   ["imperva", "incapsula"],
        "cookies":  ["incap_ses", "visid_incap", "nlbi_"],
        "body":     ["incapsula", "imperva", "robot check", "_Incapsula_Resource"],
        "codes":    [403, 412],
        "color":    RD,
        "bypass":   [
            "Imperva challenge can sometimes be bypassed with old TLS",
            "Try direct origin via X-Real-IP",
            "Header smuggling: X-Forwarded-For: 127.0.0.1",
        ]
    },
    "ModSecurity": {
        "headers":  ["x-modsec", "x-modsecurity"],
        "server":   ["mod_security", "modsecurity"],
        "cookies":  [],
        "body":     ["mod_security", "modsecurity", "not acceptable",
                     "406 not acceptable", "this error was generated by mod_security"],
        "codes":    [403, 406],
        "color":    G1,
        "bypass":   [
            "ModSecurity rules vary — try encoding: URL, HTML, Unicode",
            "HTTP Parameter Pollution (HPP)",
            "Comment injection in SQL: /*!UNION*/",
            "Case variation: SeLeCt, uNiOn",
        ]
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-cnection", "x-wa-info", "bigipserver"],
        "server":   ["big-ip", "bigip"],
        "cookies":  ["ts", "f5_cspm", "MRHSession", "BIGipServer"],
        "body":     ["the requested url was rejected", "bigip", "f5 networks"],
        "codes":    [403],
        "color":    CY,
        "bypass":   [
            "F5 ASM: try multipart/form-data encoding",
            "Null byte injection: param=%00payload",
            "HPP: param=safe&param=payload",
        ]
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "server":   ["sucuri"],
        "cookies":  [],
        "body":     ["sucuri websitecheck", "access denied - sucuri",
                     "cloudproxy - sucuri"],
        "codes":    [403, 503],
        "color":    G2,
        "bypass":   [
            "Sucuri is WAF+CDN: find direct origin IP",
            "Check DNS history for pre-Sucuri IP (SecurityTrails, Shodan)",
        ]
    },
    "Barracuda": {
        "headers":  ["x-barracuda-connect", "barra_counter_session"],
        "server":   ["barracuda"],
        "cookies":  ["barra_counter_session"],
        "body":     ["barracuda networks", "barracuda web application firewall"],
        "codes":    [403],
        "color":    OR,
        "bypass":   [
            "Barracuda: try chunked transfer encoding",
            "Double encoding: %2527 instead of %27",
        ]
    },
    "Wordfence": {
        "headers":  [],
        "server":   [],
        "cookies":  ["wfvt_"],
        "body":     ["generated by wordfence", "wordfence is blocking you",
                     "your access to this site has been limited by the site owner"],
        "codes":    [403],
        "color":    G1,
        "bypass":   [
            "Wordfence: IP rotation often works",
            "Try different User-Agents",
            "Slow scan (rate limit bypass)",
        ]
    },
    "Nginx (generic)": {
        "headers":  [],
        "server":   ["nginx"],
        "cookies":  [],
        "body":     ["nginx", "400 bad request", "403 forbidden"],
        "codes":    [],
        "color":    DM,
        "bypass":   ["Generic Nginx — check for additional WAF behind it"]
    },
    "Apache (generic)": {
        "headers":  [],
        "server":   ["apache"],
        "cookies":  [],
        "body":     ["apache", "apache/2"],
        "codes":    [],
        "color":    DM,
        "bypass":   ["Generic Apache — check for mod_security or additional WAF"]
    },
}

# ─── PROBE PAYLOADS ──────────────────────────────────────────

WAF_PROBES = [
    ("SQLi basic",    "/?id=1'"),
    ("XSS basic",     "/?q=<script>alert(1)</script>"),
    ("SQLi union",    "/?id=1 UNION SELECT 1,2,3--"),
    ("Path traversal","/../../../etc/passwd"),
    ("Null byte",     "/?file=../etc/passwd%00"),
    ("LFI php",       "/?page=php://filter/convert.base64-encode/resource=index"),
    ("CMDi basic",    "/?cmd=;id"),
    ("XSS svg",       "/?x=<svg/onload=alert(1)>"),
]

NORMAL_HEADERS = {
    "User-Agent":      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
    "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection":      "keep-alive",
}

# ─── DETECTION ENGINE ────────────────────────────────────────

def _normalize_url(target: str) -> str:
    if "://" not in target:
        target = "https://" + target
    return target.rstrip("/")

def detect_waf(target: str, probe: bool = True) -> dict:
    """Retourne dict: {waf_name: score, ...} et les détails de détection"""
    url  = _normalize_url(target)
    results = {}
    raw_headers = {}
    raw_cookies = {}
    body_lower  = ""
    status      = 0

    # 1. Requête normale
    try:
        r = requests.get(url, headers=NORMAL_HEADERS, timeout=12,
                         allow_redirects=True, verify=False, proxies=_px())
        status      = r.status_code
        raw_headers = {k.lower(): v.lower() for k, v in r.headers.items()}
        raw_cookies = {k.lower(): v.lower() for k, v in r.cookies.items()}
        body_lower  = r.text.lower()[:8000]
    except Exception as e:
        return {"error": str(e)}

    # 2. Scoring par signature
    for waf_name, sig in WAF_DB.items():
        score   = 0
        matched = []

        for h in sig["headers"]:
            if h in raw_headers:
                score += 25
                matched.append(f"header:{h}")

        srv = raw_headers.get("server", "")
        for s in sig["server"]:
            if s in srv:
                score += 20
                matched.append(f"server:{s}")

        for c in sig["cookies"]:
            if any(c.lower() in k for k in raw_cookies):
                score += 20
                matched.append(f"cookie:{c}")

        for b in sig["body"]:
            if b in body_lower:
                score += 15
                matched.append(f"body:{b[:30]}")

        if status in sig["codes"] and sig["codes"]:
            score += 5

        if score > 0:
            results[waf_name] = {"score": score, "matched": matched,
                                 "color": sig["color"],
                                 "bypass": sig["bypass"]}

    # 3. Probes WAF (envoie des payloads)
    if probe and results:
        probe_results = []
        for probe_name, probe_path in WAF_PROBES[:4]:
            try:
                r2 = requests.get(url + probe_path, headers=NORMAL_HEADERS, timeout=10,
                                  timeout=8, allow_redirects=False, verify=False, proxies=_px())
                probe_results.append((probe_name, r2.status_code, probe_path))
                time.sleep(0.3)
            except Exception:
                probe_results.append((probe_name, 0, probe_path))
        return {"waf": results, "status": status,
                "server": raw_headers.get("server","?"),
                "probes": probe_results,
                "headers_seen": dict(list(raw_headers.items())[:12])}

    return {"waf": results, "status": status,
            "server": raw_headers.get("server","?"),
            "probes": [], "headers_seen": dict(list(raw_headers.items())[:12])}

# ─── DISPLAY ─────────────────────────────────────────────────

def _display_results(target: str, data: dict):
    if "error" in data:
        err(f"Request failed: {data['error']}"); return

    console.print()
    info(f"Target: [{CY}]{target}[/]  HTTP: [{G1}]{data['status']}[/]  "
         f"Server: [{OR}]{data['server']}[/]")
    console.print()

    waf = data.get("waf", {})
    if not waf:
        ok("No WAF/CDN signatures detected — target may be unprotected or use custom WAF")
    else:
        # Trier par score
        sorted_waf = sorted(waf.items(), key=lambda x: x[1]["score"], reverse=True)
        top_name, top_data = sorted_waf[0]

        if top_data["score"] >= 40:
            find(f"WAF detected: [{top_data['color']}]{top_name}[/]  "
                 f"(confidence: [{G1}]{min(top_data['score'],100)}%[/])")
        else:
            warn(f"Possible WAF: [{top_data['color']}]{top_name}[/]  "
                 f"(confidence: [{OR}]{top_data['score']}%[/])")

        # Table des résultats
        t = Table(box=box.SIMPLE, header_style=CY, border_style=G2,
                  show_edge=False, show_lines=False)
        t.add_column("WAF / CDN",   style=f"bold {G1}", width=25)
        t.add_column("Confidence",  style=CY, width=12)
        t.add_column("Evidence",    style=DM)

        for name, d in sorted_waf:
            conf = min(d["score"], 100)
            c = G1 if conf >= 60 else (OR if conf >= 30 else DM)
            matched_str = ", ".join(d["matched"][:4])
            t.add_row(name, f"[{c}]{conf}%[/]", matched_str)
        console.print(t)

        # Bypass hints
        console.print()
        console.print(Panel(
            "\n".join(f"  [{G1}]▸[/] {h}" for h in top_data["bypass"]),
            title=f"[{OR}]◈ Bypass hints for {top_name} ◈",
            border_style=OR
        ))

    # Probes
    if data.get("probes"):
        console.print()
        probe_rows = []
        for name, code, path in data["probes"]:
            c = G1 if code == 200 else (OR if code in (301,302) else RD)
            probe_rows.append((name, f"[{c}]{code}[/]", path))
        print_result_table("WAF Probe Results", ["Probe","Status","Path"], probe_rows)

    # Headers
    console.print()
    t2 = Table(box=box.SIMPLE, header_style=CY, border_style=G2, show_edge=False)
    t2.add_column("Header",  style=CY, width=30)
    t2.add_column("Value",   style=DM)
    for k, v in data.get("headers_seen", {}).items():
        t2.add_row(k, v[:80])
    console.print(t2)

def _save(target: str, data: dict):
    os.makedirs("data", exist_ok=True)
    fname = f"data/waf_{target.replace('https://','').replace('http://','').replace('/','_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(fname, "w", encoding="utf-8") as f:
        import json
        d = {"target": target, **data}
        d["waf"] = {k: {**v, "color": str(v.get("color",""))} for k,v in d.get("waf",{}).items()}
        json.dump(d, f, indent=2)
    ok(f"Saved: {fname}")

# ─── MAIN ────────────────────────────────────────────────────

def run():
    show_module_banner("waf")
    cat_talk(CAT_SCAN, "WAF fingerprinting engine loaded.", OR)
    console.print()

    if not HAS_REQUESTS:
        err("requests library required."); return

    while True:
        console.print(f"  [{G1}][1][/] WAF / CDN detect  (single target)")
        console.print(f"  [{G1}][2][/] Batch scan  (list of URLs)")
        console.print(f"  [{G1}][0][/] Back")
        console.print()
        choice = ask_choice("WAF", "0")

        if choice == "0": break

        elif choice == "1":
            console.print(Rule(f"[{G1}] WAF FINGERPRINT ", style=G2))
            target = Prompt.ask(f"  [{G1}]◈ Target (URL / domain)[/]").strip()
            if not target: continue
            probe  = Confirm.ask(f"  [{OR}]◈ Send probe payloads (noisy)?[/]", default=True)
            console.print()
            with Progress(SpinnerColumn(style=G1),
                          TextColumn(f"[{G1}]Fingerprinting {{task.description}}"),
                          TimeElapsedColumn(), console=console) as p:
                t = p.add_task(target, total=None)
                data = detect_waf(target, probe)
            _display_results(target, data)
            _save(target, data)

        elif choice == "2":
            path = Prompt.ask(f"  [{G1}]◈ File with URLs (one per line)[/]").strip()
            if not os.path.exists(path):
                err(f"File not found: {path}"); continue
            urls = [l.strip() for l in open(path, encoding="utf-8") if l.strip()]
            info(f"Scanning {len(urls)} targets...")
            for u in urls:
                console.print(f"\n  [{G2}]──────── {u} ────────[/]")
                data = detect_waf(u, probe=False)
                waf  = data.get("waf", {})
                if waf:
                    top = max(waf, key=lambda x: waf[x]["score"])
                    find(f"{u} → [{OR}]{top}[/]  ({min(waf[top]['score'],100)}%)")
                else:
                    ok(f"{u} → No WAF detected")
        console.print()

def _banner():
    logo = Text(r"""
 ██╗    ██╗ █████╗ ███████╗
 ██║    ██║██╔══██╗██╔════╝
 ██║ █╗ ██║███████║█████╗
 ██║███╗██║██╔══██║██╔══╝
 ╚███╔███╔╝██║  ██║██║
  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝
   [CLOUDFLARE · AKAMAI · AWS · IMPERVA · MODSEC · F5...]""",
        style=f"bold {CY}")
    console.print(Panel(Align(logo, align="center"), border_style=CY, padding=(0,1)))
